
package lk.ijse.nrsms.view;

import lk.ijse.nrsms.view.AttendenceManageView;
import lk.ijse.nrsms.view.ExamManagerView;
import lk.ijse.nrsms.view.HomeworkManageView;
import lk.ijse.nrsms.view.PayamentManageView;
import lk.ijse.nrsms.view.ScheduleManagerView;
import lk.ijse.nrsms.view.StudentManagerView;
import lk.ijse.nrsms.view.SessionManagerView;
import lk.ijse.nrsms.view.CenterManagerView;




public class DetailManagerView extends javax.swing.JFrame {

    /**
     * Creates new form DetailManagerView
     */
    public DetailManagerView() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnBack = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStudents = new javax.swing.JButton();
        jbtnPayments = new javax.swing.JButton();
        jbtnSchedule = new javax.swing.JButton();
        jbtnExams = new javax.swing.JButton();
        jbtnHomeworks = new javax.swing.JButton();
        jbtnAttendence = new javax.swing.JButton();
        jbtnSessions = new javax.swing.JButton();
        jbtnCenters = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/nrsms/view/back.png"))); // NOI18N
        jbtnBack.setContentAreaFilled(false);
        jbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLabel16.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel16.setText("Detail Manager");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Pro Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nayanajith Rathnayaka Student Managment System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        btnStudents.setBackground(new java.awt.Color(255, 255, 255));
        btnStudents.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        btnStudents.setText("Students");
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 50));

        jbtnPayments.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPayments.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnPayments.setText("Payments");
        jbtnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaymentsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 300, 50));

        jbtnSchedule.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSchedule.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnSchedule.setText("Schedule");
        jbtnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnScheduleActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 300, 50));

        jbtnExams.setBackground(new java.awt.Color(255, 255, 255));
        jbtnExams.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnExams.setText("Exams");
        jbtnExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExamsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 300, 50));

        jbtnHomeworks.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHomeworks.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnHomeworks.setText("Homeworks");
        jbtnHomeworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeworksActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHomeworks, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 300, 50));

        jbtnAttendence.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAttendence.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnAttendence.setText("Attendence");
        jbtnAttendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAttendenceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAttendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 300, 50));

        jbtnSessions.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSessions.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnSessions.setText("Sessions");
        jbtnSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSessionsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSessions, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 300, 50));

        jbtnCenters.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCenters.setFont(new java.awt.Font("Myanmar Text", 1, 27)); // NOI18N
        jbtnCenters.setText("Centers");
        jbtnCenters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCentersActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCenters, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 300, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/nrsms/view/cover.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 1200, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
            dispose();
            lk.ijse.nrsms.view.StudentManagerView info = new lk.ijse.nrsms.view.StudentManagerView();
            info.setVisible(true);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void jbtnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaymentsActionPerformed
            dispose();
            lk.ijse.nrsms.view.PayamentManageView info = new lk.ijse.nrsms.view.PayamentManageView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnPaymentsActionPerformed

    private void jbtnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnScheduleActionPerformed
            dispose();
            lk.ijse.nrsms.view.ScheduleManagerView info = new lk.ijse.nrsms.view.ScheduleManagerView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnScheduleActionPerformed

    private void jbtnExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExamsActionPerformed
            dispose();
            lk.ijse.nrsms.view.ExamManagerView info = new lk.ijse.nrsms.view.ExamManagerView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnExamsActionPerformed

    private void jbtnHomeworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeworksActionPerformed
            dispose();
            lk.ijse.nrsms.view.HomeworkManageView info = new lk.ijse.nrsms.view.HomeworkManageView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnHomeworksActionPerformed

    private void jbtnAttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAttendenceActionPerformed
            dispose();
            lk.ijse.nrsms.view.AttendenceManageView info = new lk.ijse.nrsms.view.AttendenceManageView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnAttendenceActionPerformed

    private void jbtnSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSessionsActionPerformed
            dispose();
            lk.ijse.nrsms.view.SessionManagerView info = new lk.ijse.nrsms.view.SessionManagerView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnSessionsActionPerformed

    private void jbtnCentersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCentersActionPerformed
            dispose();
            lk.ijse.nrsms.view.CenterManagerView info = new lk.ijse.nrsms.view.CenterManagerView();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnCentersActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        dispose();
        lk.ijse.nrsms.view.ConsoleView fuck = new lk.ijse.nrsms.view.ConsoleView();
        fuck.setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnAttendence;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnCenters;
    private javax.swing.JButton jbtnExams;
    private javax.swing.JButton jbtnHomeworks;
    private javax.swing.JButton jbtnPayments;
    private javax.swing.JButton jbtnSchedule;
    private javax.swing.JButton jbtnSessions;
    // End of variables declaration//GEN-END:variables
}
