/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.nrsms.view;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.nrsms.controller.ScheduleController;
import lk.ijse.nrsms.model.Schedule;


/**
 *
 * @author vimuk
 */
public class ScheduleManagerView extends javax.swing.JFrame {

    /**
     * Creates new form ScheduleManagerView
     */
    public ScheduleManagerView() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSCHID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSHStart = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSCHD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel16.setText("Schedule Details Manager");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 480, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Pro Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nayanajith Rathnayaka Student Managment System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/nrsms/view/back.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel2.setText("SCHID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 20));

        txtSCHID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSCHIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSCHID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 230, 40));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 230, 40));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 50, 20));
        jPanel1.add(txtSHStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 230, 40));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel4.setText("Start");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 50, 20));
        jPanel1.add(txtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 230, 40));

        jLabel5.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel5.setText("End");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 50, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/nrsms/view/cover2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 1210, 260));

        btnDelete.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 200, 40));

        btnSave.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 200, 40));

        btnUpdate.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 200, 40));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel7.setText("Record Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, -1, -1));

        txtSCHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSCHDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSCHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 120, 60, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record Number", "Schedule ID", "Date", "Start", "End"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 730, 70));

        jButton1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton1.setText("Apply");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       dispose();
       lk.ijse.nrsms.view.DetailManagerView info = new lk.ijse.nrsms.view.DetailManagerView();
       info.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        try {
            String SCHD = null;
            String SCHID = txtSCHID.getText();
            String SHDate = txtDate.getText();
            String SHStart = txtSHStart.getText();
            String SHEnd = txtEnd.getText();
            
            Schedule s1 = new Schedule(
                    SCHD,
                    SCHID,
                    SHDate,
                    SHStart,
                    SHEnd
            );
            
            boolean isSaved = new ScheduleController().saveSchedule(s1);
            
            if(isSaved){
            JOptionPane.showMessageDialog(null, "Saved");
            }else{
            JOptionPane.showMessageDialog(null, "Try again");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSCHIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSCHIDActionPerformed
       
    }//GEN-LAST:event_txtSCHIDActionPerformed

    private void txtSCHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSCHDActionPerformed
        
        if(txtSCHD.getText().trim().length()>0){
            try {
                Schedule OBJ = new ScheduleController().getSchedule(txtSCHD.getText().trim());
                if(OBJ!=null){
                    
                    txtSCHID.setText(OBJ.getSCHID());
                    txtDate.setText(OBJ.getSHDate());
                    txtSHStart.setText(OBJ.getSHStart());
                    txtEnd.setText(OBJ.getSHEnd());
                }else{
                    JOptionPane.showMessageDialog(this, "No results found", "Warning", JOptionPane.WARNING_MESSAGE);
                }   } catch (SQLException ex) {
                Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        JOptionPane.showMessageDialog(this, "Please Insert Record Number", "Error", JOptionPane.ERROR_MESSAGE);
        
        }    
    }//GEN-LAST:event_txtSCHDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       if(txtSCHD.getText().trim().length()>0){
           try {
               if(new ScheduleController().dropSchedule(txtSCHD.getText().trim())){
                   JOptionPane.showMessageDialog(this, "Deleted...");
               }else{
                   JOptionPane.showMessageDialog(null, "Something went wrong!!!","Warning",JOptionPane.WARNING_MESSAGE);
               }   
           } catch (SQLException ex) {
               Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(ScheduleManagerView.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();

        int rowNumber = isAlreadyExists(txtSCHID.getText());

        if (rowNumber == -1) {
            Object rowData[] = {
                txtSCHID.getText(),
                txtSCHD.getText(),
                txtDate.getText(),
                txtDate.getText(),
                txtSHStart.getText(),
                txtEnd.getText()
                
            };

            modal.addRow(rowData);
        }else{
            /*qty+=(int)modal.getValueAt(rowNumber, 2);
            total=qty*unitPrice;
            tbl.setValueAt(qty, rowNumber, 2);
            tbl.setValueAt(total, rowNumber, 4);*/
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtSCHD;
    private javax.swing.JTextField txtSCHID;
    private javax.swing.JTextField txtSHStart;
    // End of variables declaration//GEN-END:variables

    private int isAlreadyExists(String code) {
        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();

        for (int i = 0; i < modal.getRowCount(); i++) {
            String temp = (String) modal.getValueAt(i, 0);
            if (temp.equals(code)) {
                return i;
            }
        }

        return -1;
    }
}
