/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.nrsms.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.nrsms.controller.StudentController;
import lk.ijse.nrsms.model.Student;

/**
 *
 * @author vimuk
 */
public class StudentManagerView extends javax.swing.JFrame {

    /**
     * Creates new form SdudentManagerView
     */
    public StudentManagerView() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTeleM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTeleH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTClass = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnUnRegister = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Pro Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nayanajith Rathnayaka Student Managment System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/nrsms/view/back.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jLabel16.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel16.setText("Student Details Manager");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 490, 40));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 620, 40));

        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, 40));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 80, 20));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel3.setText("SID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 80, 20));

        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });
        jPanel1.add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 500, 40));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel4.setText("School");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 80, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 840, 40));

        jLabel5.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 80, 20));

        txtTeleM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleMActionPerformed(evt);
            }
        });
        jPanel1.add(txtTeleM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 400, 40));

        jLabel6.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel6.setText("Tele M");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 80, 20));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel7.setText("Class");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 40, 20));

        txtTeleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleHActionPerformed(evt);
            }
        });
        jPanel1.add(txtTeleH, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 410, 40));

        jLabel8.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jLabel8.setText("Tele H");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 80, 20));

        cmbTClass.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        cmbTClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory", "Revision" }));
        jPanel1.add(cmbTClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 310, 40));

        btnUpdate.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnUpdate.setText("Update Student");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 690, 240, 50));

        btnUnRegister.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnUnRegister.setText("Unregister Student");
        btnUnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, 240, 50));

        btnRegister.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnRegister.setText("Register Student");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 690, 240, 50));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Name", "Address", "School", "Class", "Tele M", "Tele H"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 1230, 90));

        jButton1.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
        if(txtSID.getText().trim().length()>0){
            try {
                Student OBJ = new StudentController().getStudent(txtSID.getText().trim());
                
                if(OBJ!=null){
                    txtName.setText(OBJ.getName());
                    txtAddress.setText(OBJ.getAddress());
                    txtSchool.setText(OBJ.getSchool());
                    cmbTClass.setSelectedItem(OBJ.getClass());
                    txtTeleM.setText(OBJ.getTeleM());
                    txtTeleH.setText(OBJ.getTeleH());
                    
                }else{
                    JOptionPane.showMessageDialog(this, "No Results Found","Warning",JOptionPane.WARNING_MESSAGE); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
        JOptionPane.showMessageDialog(this, "Please Insert an SID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSIDActionPerformed

    private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTeleMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleMActionPerformed

    private void txtTeleHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleHActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        if(txtSID.getText().trim().length()>4){
            
            try {
                String SID = txtSID.getText();
                String Name = txtName.getText();
                String Address = txtAddress.getText();
                String School = txtSchool.getText();
                String TClass = cmbTClass.getSelectedItem().toString();
                String TeleM = txtTeleM.getText();
                String TeleH = txtTeleH.getText();
                
                Student s1 = new Student(SID,Name,Address,School,TClass,TeleM,TeleH);
                
                if(new StudentController().updateState(s1)){
                    JOptionPane.showMessageDialog(null, "Done...");
                }else{
                    JOptionPane.showMessageDialog(null, "Please try again", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Please Insert Correct ID", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnRegisterActionPerformed
       if(txtSID.getText().trim().length()>5){
           try {
               if(new StudentController().dropStudent(txtSID.getText().trim())){
                   JOptionPane.showMessageDialog(null, "Deleted...");
               }   
           } catch (SQLException ex) {
               Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else{
       JOptionPane.showMessageDialog(null, "Something went wrong!!!","Warning",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnUnRegisterActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
       
        try {
            String SID = txtSID.getText();
            String Name = txtName.getText();
            String Address = txtAddress.getText();
            String School = txtSchool.getText();
            String TClass = cmbTClass.getSelectedItem().toString();
            String TeleM = txtTeleM.getText();
            String TeleH = txtTeleH.getText();
            
            Student s1 = new Student(
                    SID,
                    Name,
                    Address,
                    School,
                    TClass,
                    TeleM,
                    TeleH
            );
            
            boolean isSaved = new StudentController().saveStudent(s1);
        if(isSaved){
        //save
            JOptionPane.showMessageDialog(null,"Saved");
        }else{
        //fail
         JOptionPane.showMessageDialog(null,"Try Again");
        }
        
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentManagerView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        lk.ijse.nrsms.view.DetailManagerView info = new lk.ijse.nrsms.view.DetailManagerView();
        info.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();

        int rowNumber = isAlreadyExists(txtSID.getText());

        if (rowNumber == -1) {
            Object rowData[] = {
                txtSID.getText(),
                txtName.getText(),
                txtAddress.getText(),
                txtSchool.getText(),
                cmbTClass.getSelectedItem().toString(),
                txtTeleM.getText(),
                txtTeleH.getText()
            };

            modal.addRow(rowData);
        }else{
            /*qty+=(int)modal.getValueAt(rowNumber, 2);
            total=qty*unitPrice;
            tbl.setValueAt(qty, rowNumber, 2);
            tbl.setValueAt(total, rowNumber, 4);*/
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbTClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSchool;
    private javax.swing.JTextField txtTeleH;
    private javax.swing.JTextField txtTeleM;
    // End of variables declaration//GEN-END:variables

    private int isAlreadyExists(String code) {
        
        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();

        for (int i = 0; i < modal.getRowCount(); i++) {
            String temp = (String) modal.getValueAt(i, 0);
            if (temp.equals(code)) {
                return i;
            }
        }

        return -1;
    }
}
